# permissions for end users to edit groupsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: groupsync-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - groupsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - groupsyncs/status
  verbs:
  - get
