apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: groupsyncs.redhatcop.redhat.io
spec:
  group: redhatcop.redhat.io
  names:
    kind: GroupSync
    listKind: GroupSyncList
    plural: groupsyncs
    singular: groupsync
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: GroupSync is the Schema for the groupsyncs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: GroupSyncSpec defines the desired state of GroupSync
          properties:
            providers:
              description: List of Providers that can be mounted by containers belonging
                to the pod.
              items:
                description: Provider represents the container for a single provider
                properties:
                  azure:
                    description: AzureProvider represents integration with Azure
                    properties:
                      credentialsSecretName:
                        type: string
                      groups:
                        items:
                          type: string
                        type: array
                      insecure:
                        type: boolean
                      url:
                        type: string
                    required:
                    - credentialsSecretName
                    type: object
                  github:
                    description: GitHubProvider represents integration with GitHub
                    properties:
                      caSecretRef:
                        description: SecretRef represents a reference to an item within
                          a Secret
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                        required:
                        - name
                        type: object
                      credentialsSecretName:
                        type: string
                      insecure:
                        type: boolean
                      organization:
                        type: string
                      teams:
                        items:
                          type: string
                        type: array
                      url:
                        type: string
                    required:
                    - credentialsSecretName
                    type: object
                  gitlab:
                    description: GitLabProvider represents integration with GitLab
                    properties:
                      caSecretRef:
                        description: SecretRef represents a reference to an item within
                          a Secret
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                        required:
                        - name
                        type: object
                      credentialsSecretName:
                        type: string
                      groups:
                        items:
                          type: string
                        type: array
                      insecure:
                        type: boolean
                      url:
                        type: string
                    required:
                    - credentialsSecretName
                    type: object
                  keycloak:
                    description: KeycloakProvider represents integration with Keycloak
                    properties:
                      caSecretRef:
                        description: SecretRef represents a reference to an item within
                          a Secret
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                        required:
                        - name
                        type: object
                      credentialsSecretName:
                        type: string
                      groups:
                        items:
                          type: string
                        type: array
                      insecure:
                        type: boolean
                      loginRealm:
                        type: string
                      realm:
                        type: string
                      scope:
                        enum:
                        - one
                        - sub
                        type: string
                      url:
                        type: string
                    required:
                    - credentialsSecretName
                    - realm
                    - url
                    type: object
                  name:
                    type: string
                required:
                - name
                type: object
              type: array
            schedule:
              type: string
          type: object
        status:
          description: GroupSyncStatus defines the observed state of GroupSync
          properties:
            conditions:
              additionalProperties:
                description: "Condition represents an observation of an object's state.
                  Conditions are an extension mechanism intended to be used when the
                  details of an observation are not a priori known or would not apply
                  to all instances of a given Kind. \n Conditions should be added
                  to explicitly convey properties that users and components care about
                  rather than requiring those properties to be inferred from other
                  observations. Once defined, the meaning of a Condition can not be
                  changed arbitrarily - it becomes part of the API, and has the same
                  backwards- and forwards-compatibility concerns of any other part
                  of the API."
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    description: ConditionReason is intended to be a one-word, CamelCase
                      representation of the category of cause of the current status.
                      It is intended to be used in concise output, such as one-line
                      kubectl get output, and in summarizing occurrences of causes.
                    type: string
                  status:
                    type: string
                  type:
                    description: "ConditionType is the type of the condition and is
                      typically a CamelCased word or short phrase. \n Condition types
                      should indicate state in the \"abnormal-true\" polarity. For
                      example, if the condition indicates when a policy is invalid,
                      the \"is valid\" case is probably the norm, so the condition
                      should be called \"Invalid\"."
                    type: string
                required:
                - status
                - type
                type: object
              description: Conditions is a set of Condition instances.
              type: array
            lastSyncSuccessTime:
              format: date-time
              type: string
          required:
          - conditions
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
