kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: group-sync-operator
subjects:
  - kind: ServiceAccount
    name: group-sync-operator
    namespace: group-sync-operator
roleRef:
  kind: ClusterRole
  name: group-sync-operator
  apiGroup: rbac.authorization.k8s.io
