apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: group-sync-operator
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - user.openshift.io
    resources:
      - groups
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - redhatcop.redhat.io
    resources:
      - groupsyncs
      - groupsyncs/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
