apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: keycloak-groupsync
spec:
  providers:
    - name: keycloak
      keycloak:
        realm: ocp
        url: "https://keycloak-keycloak-operator.apps.openshift.com"
        credentialsSecretName: keycloak-group-sync
