apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: keycloak-groupsync
spec:
  providers:
    - name: keycloak
      keycloak:
        insecure: true
        realm: ocp
        url: "https://keycloak-keycloak-operator.apps.cluster-a8b1.a8b1.example.opentlc.com"
        secretName: keycloak-group-sync
